### ISSUE TITLE
First RUN

### ISSUE THREAD

**Issue by ffdown** [andreasfloros/RWNN#2]
python train.py --should_prepare True

PyTorch is running on NVIDIA GeForce RTX 4090

training set # samples 43200
validation set # samples 100
# transform parameters: 170144
# total model parameters: 296635

Traceback (most recent call last):
  File "E:\AI\RWNN\train.py", line 50, in <module>
    dtmins, info = coordinator.train()
  File "E:\AI\RWNN\coordinator\coordinator.py", line 71, in train
    fyi, loss = self.model.module.get_training_loss(data)
  File "E:\AI\RWNN\coordinator\wrapper.py", line 26, in get_training_loss
    res, ne = self.alg(inp, layer = self.decode_depth, show_ne = True)
  File "E:\AI\RWNN\coordinator\wrapper_algorithms.py", line 16, in dae
    [cn, dn], nes = self.transform_net.forward(x, map = map, J = layer)
  File "E:\AI\RWNN\models\transform_model.py", line 35, in forward
    x, yd = self.inn(x, ne)
  File "E:\AI\RWNN\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\RWNN\models\inn.py", line 14, in forward
    x = lift(x, sigma)
  File "E:\AI\RWNN\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\RWNN\models\inn.py", line 40, in forward
    c = c + self.u(nd, sigma)
  File "E:\AI\RWNN\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\RWNN\models\inn.py", line 68, in forward
    return self.net(x, sigma)
  File "E:\AI\RWNN\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_add_relu(float* tout_7, float* tthreshold_2, float* tsigma_1, float* aten_relu) {
{
  float tout_7_1 = __ldg(tout_7 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  float tthreshold_2_1 = __ldg(tthreshold_2 + (((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) / 1024ll) % 32ll);
  float tsigma_1_1 = __ldg(tsigma_1 + 0ll);
  aten_relu[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = tout_7_1 + tthreshold_2_1 * tsigma_1_1<0.f ? 0.f : tout_7_1 + tthreshold_2_1 * tsigma_1_1;
}
}

**Comment by andreasfloros** [comment]
Hi @ffdown, not sure if the scripting is causing the problem but I've removed it now.
In case the problem persists, could you share which PyTorch version you are using?
